name: Self-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write

jobs:
  selftest:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        uses: ./
        id: ansible-sign
        with:
          project_path: ./test/
      - name: Check outputs
        run: |
          [[ -f ./test/.ansible-sign/sha256sum.txt.sigstore ]] || exit 1

  selftest-xfail-invalid-inputs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_path:
          # We forbid inputs that look like flags
          - "--this-should-not-work"
          # We fail if the input doesn't exist
          - "/tmp/extremely-nonexistent-project-path/"
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        continue-on-error: true
        uses: ./
        id: ansible-sign
        with:
          project_path: ${{ matrix.project_path }}
      - name: Check failure
        env:
          XFAIL: ${{ steps.ansible-sign.outcome == 'failure' }}
          JOB_NAME: ${{ github.job }}
        run: |
          echo "xfail ${JOB_NAME}: ${XFAIL}"

          [[ "${XFAIL}" == "true" ]] || { >&2 echo "expected step to fail"; exit 1; }

  selftest-staging:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        uses: ./
        id: ansible-sign
        with:
          project_path: ./test/
          staging: true
      - name: Check outputs
        run: |
          [[ -f ./test/.ansible-sign/sha256sum.txt.sigstore ]] || exit 1

  selftest-glob:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifacts and publish signatures
        uses: ./
        id: ansible-sign
        with:
          project_path: ./test/
          staging: true

  selftest-upload-artifacts:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        uses: ./
        id: ansible-sign
        with:
          project_path: ./test/
          staging: true
          upload-signing-artifacts: true
      - uses: actions/download-artifact@v3
        with:
          name: "signing-artifacts-${{ github.job }}"
          path: ./test/uploaded
      - name: Verify presence of uploaded files
        run: |
          [[ -f ./artifact.txt ]] || exit 1
          [[ -f ./.ansible-sign/artifact.txt.sigstore ]] || exit 1
        working-directory: ./test/uploaded

  selftest-verify:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        uses: ./
        id: ansible-sign
        with:
          project_path: ./test/
          verify: true
          verify-cert-identity: https://github.com/mayaCostantini/sigstore-ansible-github-action/.github/workflows/selftest.yml@${{ github.ref }}
          verify-oidc-issuer: https://token.actions.githubusercontent.com
          staging: true

  selftest-xfail-verify-missing-options:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # fails if both verify-cert-identity and verify-oidc-issuer are missing
          - verify: true

          # fails if either is missing
          - verify: true
            verify-oidc-issuer: https://token.actions.githubusercontent.com

          - verify: true
            verify-cert-identity: https://github.com/mayaCostantini/sigstore-ansible-github-action/.github/workflows/selftest.yml@${{ github.ref }}

          # fails if either option is passed while verification is disabled
          - verify: false
            verify-oidc-issuer: https://token.actions.githubusercontent.com

          - verify: false
            verify-cert-identity: https://github.com/mayaCostantini/sigstore-ansible-github-actionn/.github/workflows/selftest.yml@${{ github.ref }}

    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        continue-on-error: true
        uses: ./
        id: ansible-sign
        with:
          project_path: ./test/
          verify: ${{ matrix.config.verify }}
          verify-oidc-issuer: ${{ matrix.config.verify-oidc-issuer }}
          verify-cert-identity: ${{ matrix.config.verify-cert-identity }}
          staging: true
      - name: Check failure
        env:
          XFAIL: ${{ steps.ansible-sign.outcome == 'failure' }}
          JOB_NAME: ${{ github.job }}
        run: |
          echo "xfail ${JOB_NAME}: ${XFAIL}"

          [[ "${XFAIL}" == "true" ]] || { >&2 echo "expected step to fail"; exit 1; }

  selftest-identity-token:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v3
      - name: Get OIDC token
        id: get-oidc-token
        run: |
          identity_token=$( \
            curl -H \
              "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" \
            | jq -r .value \
          )
          echo "identity-token=$identity_token" >> $GITHUB_OUTPUT
        shell: bash
      - name: Sign artifact and publish signature
        uses: ./
        id: ansible-sign
        with:
          project_path: ./test/
          identity-token: ${{ steps.get-oidc-token.outputs.identity-token }}
          staging: true

  all-selftests-pass:
    if: always()

    needs:
      - selftest
      - selftest-xfail-invalid-inputs
      - selftest-staging
      - selftest-glob
      - selftest-upload-artifacts
      - selftest-verify
      - selftest-xfail-verify-missing-options
      - selftest-identity-token

    runs-on: ubuntu-latest

    steps:
      - name: check test jobs
        if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
